[project]
name = "ecopower-tarrifs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "influxdb-client>=1.49.0",
    "pandas>=2.3.3",
]
